angular
.module('contacts',[])
.config(function($routeProvider){
$routeProvider
.when('/contacts/:index',{
templateUrl:'edit.html',
controller:'Edit'
})
.when('/',{
templateUrl:'list.html',
});
})
.controller('Contacts',function($scope){
$scope.contacts=[
{name:"tom",number:12345},
{name:"wayne",number:46345},
{name:"robin",number:1264}
];
})
.controller('Edit',function($scope,$routeParams){
$scope.contact=$scope.contacts[$routeParams.index];
$scope.index=$routeParams.index;
});